# Generated by Django 4.2.5 on 2023-10-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('Turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('Turf_name', models.CharField(max_length=200)),
                ('Turf_address', models.CharField(max_length=250)),
                ('Turf_caption', models.CharField(max_length=200)),
                ('Turf_price', models.CharField(max_length=200)),
                ('Turf_area', models.CharField(choices=[('Calicut', 'Calicut'), ('Malappuram', 'Malappuram')], default='Calicut', max_length=200)),
                ('Turf_image', models.ImageField(blank=True, null=True, upload_to='turf_img')),
            ],
        ),
    ]
