# Generated by Django 4.2.5 on 2023-10-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_turfdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='Profile_Image',
            field=models.FileField(upload_to='turf_img'),
        ),
    ]
