# Generated by Django 4.2.5 on 2023-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_managerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='Profile_Image',
            field=models.FileField(blank=True, null=True, upload_to='turf_img'),
        ),
    ]
