# Generated by Django 4.2.5 on 2023-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_alter_turfdetails_turf_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfdetails',
            name='Turf_image',
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='Turf_img',
            field=models.ImageField(blank=True, null=True, upload_to='turf_img'),
        ),
    ]
