# Generated by Django 4.2.5 on 2023-10-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0010_rename_turf_img_turfdetails_turf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdetails',
            name='Turf_image',
            field=models.ImageField(blank=True, null=True, upload_to='turf_img'),
        ),
    ]
