# Generated by Django 4.2.5 on 2023-10-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0011_alter_turfdetails_turf_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfList',
            fields=[
                ('Turf_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Turf_name', models.CharField(max_length=200)),
                ('Turf_address', models.CharField(max_length=200)),
                ('Turf_price', models.CharField(max_length=200)),
                ('Turf_caption', models.CharField(max_length=200)),
                ('Turf_image', models.ImageField(blank=True, null=True, upload_to='turf_img')),
                ('Turf_area', models.CharField(choices=[('Calicut', 'Calicut'), ('Malappuram', 'Malappuram')], default='Calicut', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TurfDetails',
        ),
    ]
