# Generated by Django 4.2.5 on 2023-12-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0014_managermessage_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerMessage',
        ),
    ]
