# Generated by Django 4.2.7 on 2023-12-12 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0015_delete_managermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='Manager_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profiles_by_manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profiles_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
