# Generated by Django 4.2.7 on 2023-12-12 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0016_managerprofile_manager_id_alter_managerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='Manager_ID',
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
