# Generated by Django 4.2.7 on 2023-12-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '0017_remove_managerprofile_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
